
    /**
     * ⚠️ WARNING: DO NOT EDIT THIS FILE DIRECTLY ⚠️
     * 
     * This file is auto-generated.
     * Any changes made to this file will be overwritten.
     * 
     * To modify, edit the source files and re-run the generator.
     * Generated on: 2025-01-26T13:12:04.541Z
     */
      import * as dzormimp from "drizzle-orm";

      import {  pgTable, text } from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: text("id").primaryKey(),
  profileId: text("profile__id")
    .references(() => profiles.id)
    .unique(), // adding unique makes it one-to-one
});

export const jojojo = pgTable("idea", {
  id: text("id").primaryKey(),
});




export const profiles = pgTable("profile", {
  id: text("id").primaryKey(),
  content: text("content"),
});

export const posts = pgTable("post", {
  id: text("id").primaryKey(),
  content: text("content"),
  authorId: text("author_id")
});


export const jojojoRelations = dzormimp.relations(
  jojojo,
  ({ one, many }) => ({}),
);

export const postsRelations = dzormimp.relations(
  posts,
  ({ one, many }) => ({}),
);

export const profilesRelations = dzormimp.relations(
  profiles,
  ({ one, many }) => ({
    users: one(users),
  }),
);

export const usersRelations = dzormimp.relations(users, ({ one, many }) => ({
  profiles: one(profiles, {
    fields: [users.profileId],
    references: [profiles.id],
  }),
}));

    