/**
 *  WARNING: DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is auto-generated.
 * Any changes made to this file will be overwritten.
 *
 * To modify, edit the source files and re-run the generator.
 * Generated on: 2025-02-19T20:30:01.313Z
 */
import * as dzormimp from "drizzle-orm";
import * as originalSchema from "./schema";

export * from "./schema";

export const TB_messageRelations = dzormimp.relations(
  originalSchema.TB_message,
  ({ one, many }) => ({
    message_sender: one(originalSchema.TB_users, {
      fields: [originalSchema.TB_message.senderId],
      references: [originalSchema.TB_users.id],
      relationName: "message_sender",
    }),
    message_recepient: one(originalSchema.TB_users, {
      fields: [originalSchema.TB_message.recepientId],
      references: [originalSchema.TB_users.id],
      relationName: "message_recepient",
    }),
  }),
);

export const TB_postsRelations = dzormimp.relations(
  originalSchema.TB_posts,
  ({ one, many }) => ({
    TB_users: one(originalSchema.TB_users, {
      fields: [originalSchema.TB_posts.authorId],
      references: [originalSchema.TB_users.id],
    }),
  }),
);

export const TB_profileRelations = dzormimp.relations(
  originalSchema.TB_profile,
  ({ one, many }) => ({
    TB_users: one(originalSchema.TB_users, {
      fields: [originalSchema.TB_profile.userId],
      references: [originalSchema.TB_users.id],
    }),
  }),
);

export const TB_usersRelations = dzormimp.relations(
  originalSchema.TB_users,
  ({ one, many }) => ({
    TB_profile: one(originalSchema.TB_profile),
    message_sender: many(originalSchema.TB_message, {
      relationName: "message_sender",
    }),
    message_recepient: many(originalSchema.TB_message, {
      relationName: "message_recepient",
    }),
    TB_posts: many(originalSchema.TB_posts),
  }),
);
